version: '3.3'
services:
    ko-private-gpt:
      ports:
        - '7860:7860'
      container_name: KoPrivateGPT
      build:
        context: ./containers/KoPrivateGPT
      command: gradio app.py
      environment:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        PINECONE_API_KEY: ${PINECONE_API_KEY}
        PINECONE_ENV: ${PINECONE_ENV}
      platform: linux/amd64
        

    hwp-converter:
      ports:
        - '127.0.0.1:7000'
      container_name: hwp-converter
      image: 'vkehfdl1/hwp-converter-api:1.0.0'
